# Generated by Django 4.0 on 2022-03-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='categori',
            new_name='category',
        ),
    ]
