# Generated by Django 4.0 on 2022-03-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.AddField(
            model_name='items',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.categories'),
        ),
    ]
